package de.confidential.domain

enum class GamePhase {

    NOMINATING_CHANCELLOR,
    VOTING_LEADERSHIP,
    PRESIDENT_DISCARDS_POLICY_TILE,
    CHANCELLOR_DISCARDS_POLICY_TILE,
    PRESIDENT_EXECUTIVE_POWER,
    GAME_OVER
}
